language: node_js
services: docker
cache:
  directories:
    - $HOME/.npm
node_js: 12
before_script:
  - npm prune
  - npm run dependencies && sleep 10
script:
  - npm run ci
after_success:
  - npm run coveralls
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
