language: node_js
services: docker
cache:
  directories:
    - $HOME/.npm
node_js: ['12']
before_script:
  - yarn
  - docker-compose pull
  - docker-compose up -d && sleep 30
script:
  - yarn ci
after_success:
  - yarn coveralls
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
