language: node_js
services: docker
cache:
  directories:
    - $HOME/.npm
node_js: ['12']
before_script:
  - npm prune
  - docker-compose pull
  - docker-compose up -d && sleep 10
script:
  - npm run ci
after_success:
  - npm run coveralls
  - npx lerna version
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
